### ISSUE TITLE
if not signed in, hoodie.account.destroy() should still work and delete all user’s data 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-client#110]

**Comment by thomasjinlo** [comment]
Hello, I'm thinking about tackling this issue. It occurs to me that if a user is not signed in the session should be invalid, thus it makes sense not to send a [delete request](https://github.com/hoodiehq/hoodie-account-client/blob/master/lib/destroy.js#L13-#L32). Would wrapping the request in a conditional which checks session validity be a good approach? Thanks!

**Comment by gr2m** [comment]
All yours @thomasjinlo 👍 By the way don’t forget to sign up for https://hacktoberfest.digitalocean.com ;)

I would suggest we check with `.isSignedIn()`. If it returns false, don’t send the request, do as if id would have been successful

**Comment by thomasjinlo** [comment]
Thanks so much :)
