### ISSUE TITLE
when fetching account from remote succeeds, we should unset `session.invalid`

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-client#146]
should happen around these lines:

- https://github.com/hoodiehq/hoodie-account-client/blob/22d8c15994a1a1cc9e03ea256e155164965c6bc4/lib/get.js#L43
- https://github.com/hoodiehq/hoodie-account-client/blob/22d8c15994a1a1cc9e03ea256e155164965c6bc4/lib/profile-get.js#L41

if `cachedProperties.session.invalid` is true, then remove it and emit the `reauthenticate` event

**Comment by mbad0la** [comment]
Claiming this one!
