### ISSUE TITLE
Bring code coverage to 100%

### ISSUE THREAD

**Issue by toh82** [hoodiehq/hoodie-account-client#66]
current status: [![Coverage Status](https://coveralls.io/repos/github/hoodiehq/hoodie-client-account/badge.svg?branch=master)](https://coveralls.io/github/hoodiehq/hoodie-client-account?branch=master)
```
npm run test:coverage

...
=============================== Coverage summary ===============================
Statements   : 97.09% ( 400/412 )
Branches     : 91.2% ( 114/125 )
Functions    : 92.86% ( 65/70 )
Lines        : 97.09% ( 400/412 )
================================================================================
```

---
- [x] claim this issue (@chrifpa)
- [x] setup the repo locally and make sure that all tests pass when you run `npm test`
- [x] get a coverage report by running `npm run test:coverage`. That also creates a `coverage` folder. Open `coverage/lcov-report/index.html` for a nice UI that shows you exactly what lines / branches etc are not yet covered
- [x] add a test to fix one of the not covered lines / branches. Commit with `WIP #66 coverage`
- [x] start a pull request #78
- [x] write tests until 100% coverage is reached, just keep commiting all changes, don’t worry the amount of commits, we will clean them up before merging. Comment below when you are ready for review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq) if you have ​​_any_​​ questions

**Comment by chrifpa** [comment]
Starting to work on it now :)

**Comment by gr2m** [comment]
wo00ooohoo000oo :clap: done via #78 

That was a hell of a pull request, thanks a lot! And welcome to Hoodie :wave: :dog: I’ve invited you to the Hoodie Contributors team, you should see an invitation on https://github.com/hoodiehq.

Mind us giving you a shout out on Twitter? Would you like to keep contributing to Hoodie?

**Comment by chrifpa** [comment]
Thanks for the invite!

>Mind us giving you a shout out on Twitter?
Not at all :)

>Would you like to keep contributing to Hoodie?
Absolutely! Anything specific that needs doing or should I just browse the issues?

**Comment by gr2m** [comment]
> Absolutely! Anything specific that needs doing or should I just browse the issues?

I don’t have anything specific right now, browse around and see if you can find something :) Ping us anytime if you have any questions
