### ISSUE TITLE
account.update: set session ID from `x-set-session` response header

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-client#75]
follow up for https://github.com/hoodiehq/hoodie-client-account/pull/74#discussion_r52942960

Right now, we send an internal `PUT /session` request after a `PATCH /session/account` request which changed the account username and/or password.

Instead, we want the `PATCH /session/account` response to optionally include a `x-set-session` header which would include the new session id, so that it can be updated without sending an extra request

---

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) 

---

- [x] claim this issue (@gr2m)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-client-account#testing) and make sure that all tests pass
- [x] revert the changes of https://github.com/hoodiehq/hoodie-client-account/pull/74/files
- [x] update [test/integration/update-account-test.js#L19](https://github.com/hoodiehq/hoodie-client-account/blob/94844c3954c9d2bcc2e5d5f4e5127b01bec8f8ca/test/integration/update-account-test.js#L19): set a [reply header](https://www.npmjs.com/package/nock#specifying-reply-headers) for the `PATCH /session/account` response to include the `x-set-session` header with a new session id.
- [x] add [request headers](https://www.npmjs.com/package/nock#specifying-request-headers) to the `DELETE /session` request mock. Make sure the new session id is passed in the `Authorization: bearer <new session id here>` header. Make sure test fails when you run `npm test`
- [x] commit all test files with `test(update): session id`
- [x] fix the implementation in [lib/accounts/update.js](https://github.com/hoodiehq/hoodie-client-account/blob/94844c3954c9d2bcc2e5d5f4e5127b01bec8f8ca/admin/lib/accounts/update.js). We might need to change [utils/request.js](https://github.com/hoodiehq/hoodie-client-account/blob/94844c3954c9d2bcc2e5d5f4e5127b01bec8f8ca/utils/request.js) to resolve with both the response body & headers instead of just the body. Make sure tests pass when you run `npm test`
- [x] commit all changes with `fix(update): session id`
- [x] pull request: https://github.com/hoodiehq/hoodie-account-client/pull/94
- [x] Someone else: review & merge

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by steffes** [comment]
I would like to take this issue

**Comment by gr2m** [comment]
all yours @steffes :+1:

**Comment by steffes** [comment]
I'm looking to see what needs to be changed in [utils/request.js](https://github.com/hoodiehq/hoodie-client-account/blob/94844c3954c9d2bcc2e5d5f4e5127b01bec8f8ca/utils/request.js#L19). Right now L19 doesn't have a body parameter and is just `resolve(response)` at the end. You said it is resolving just the body but it does not have a `body` parameter like in the testcases of [nets/test.js](https://github.com/maxogden/nets/blob/master/test.js#L101) module.

Also what is your method for debugging (i.e. stepping through with debugger) with client APIs' in general?

**Comment by gr2m** [comment]
> is just resolve(response)

You are right, maybe it changed meanwhile, it resolves with the whole `response` object now, so `response.headers` is accessible, which is great

> Also what is your method for debugging (i.e. stepping through with debugger) with client APIs' in general?

Very good question. To be honest I don’t have a good workflow for this. I’ve seen @nathanstilwell use a cool tool where you could jump in Chrome’s dev tools to debug your node code, but can’t remember what that was again? Nathan, do you know what I mean?

**Comment by nathanstilwell** [comment]
I've used [node-inspector](https://github.com/node-inspector/node-inspector) before with occasional success. I think it wires together the node debugger with a hook into the Chrome developer tools.

**Comment by gr2m** [comment]
@steffes could you give us an update?

**Comment by steffes** [comment]
#80

**Comment by gr2m** [comment]
<img width="676" alt="screen shot 2016-03-06 at 21 44 54" src="https://cloud.githubusercontent.com/assets/39992/13559666/b2a907ba-e3e4-11e5-801d-f4bb274edcea.png">

**Comment by codyzu** [comment]
@gr2m 
from the issue description (5th checkbox)
> add request headers to the DELETE /session request mock. Make sure the new session id is passed in the Authorization: bearer <new session id here> header. Make sure test fails when you run npm test

Why `DELETE /session`? I'm missing a detail or this is a copy/paste issue? Can you clarify for me :-)

**Comment by gr2m** [comment]
doesn’t make much sense to me, probably a copy&paste issue, ignore it :) Sorry for the confusion

**Comment by gr2m** [comment]
I’ll take this over from Cody, we discussed it

**Comment by gr2m** [comment]
Pull Request is here: https://github.com/hoodiehq/hoodie-account-client/issues/94 – if you could review that’d be ace. If things look good, comment with `LGTM` 👌
