### ISSUE TITLE
bind null in object construction

### ISSUE THREAD

**Issue by ransomw** [hoodiehq/hoodie-account-client#83]
follow up for #19 / #77

replace `bind(this,` with `bind(null,` per [comments](https://github.com/hoodiehq/hoodie-client-account/pull/77/files#r53708199) in `admin/index.js`.

also consider updating object construction elsewhere in the repository with the new pattern if discussion deems appropriate.

**Comment by chrifpa** [comment]
Hey @ransomw, mind if I do this?

**Comment by gr2m** [comment]
first come first served, no need to ask :)

**Comment by chrifpa** [comment]
Okie dokie 😅
