### ISSUE TITLE
Migrate to new Architecture

### ISSUE THREAD

**Issue by finnp** [hoodiehq/hoodie-account-client#85]
part of https://github.com/hoodiehq/hoodie/issues/458

- [x] rename to `hoodie-account-client`
- [x] in `package.json`, set `"name"` to `"@hoodie/account-client"`, and add `"publishConfig": {"access": "public"}`
- [x] find `hoodie-account-client` and replace with `hoodie-account-client`
- [x] do commits as in https://github.com/hoodiehq/hoodie-log/issues/31

Once merged

- [x] deprecate `hoodie-client-account` in the npm registry
- [x] enable coveralls for new repo name (run `COVERALLS_REPO_TOKEN=... npm run coverage`, then on coveralls.io require `100%` coverage for success)
- [x] update branch protection: re-enable coveralls 

/cc @gr2m

**Comment by gr2m** [comment]
woop :clap:
