### ISSUE TITLE
README: setup instructions

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-client#88]
![welcome-to-open-source-atlanta](https://cloud.githubusercontent.com/assets/39992/13732817/58766428-e960-11e5-8496-c65891ad0835.png)

**This issue is reserved for participants of [Welcome to Open Source, Atlanta](http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/)**.
If it’s still available after April 2nd, it’s all yours :)

---

### :dart: The Goal

Currently, [testing section of this repository’s README](https://github.com/hoodiehq/hoodie-account-client#testing) has no instructions on how to setup it up locally for testing. The steps are the same as for [hoodie-client](https://github.com/hoodiehq/hoodie-client#testing), only the URL is different as it’s a different repository

### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request

- [ ] claim this issue (comment below)
- [ ] Clone the repository to your computer
- [ ] Edit the `README.md` file.
- [ ] Commit the change `docs(README): setup instructions`
- [ ] Start a Pull Request.  Mention `closes #88` in the description of the pull request
- [ ] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by marisalaneous** [comment]
claiming this

**Comment by marisalaneous** [comment]
pr ready for review
